driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
    run_list: apt::default
  - name: debian-8.1
    run_list: apt::default
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: windows-8.1

suites:
- name: default
  run_list:
    - recipe[erlang]

- name: gui_tools
  run_list:
    - recipe[erlang]
  attributes:
    erlang:
      gui_tools: true
  excludes:
    - centos-5.11
    - centos-6.7 
    - centos-7.1
    - fedora-21
    - windows-8.1

- name: esl
  run_list:
    - recipe[erlang::esl]
  excludes:
    - centos-5.11

- name: source
  run_list:
    - recipe[erlang::source]
